version: '2.4'

services:
  postgres:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=kong
    healthcheck:
      test: [CMD, bash, -c, cat < /dev/null > /dev/tcp/127.0.0.1/5432]
      interval: 5s
      timeout: 60s
      retries: 120

  oap:
    image: apache/skywalking-oap-server:8.5.0-es6
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -zn 127.0.0.1 11800"]
      interval: 5s
      timeout: 60s
      retries: 120

  kong:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 8001:8001
    environment: 
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_NGINX_HTTP_LUA_SHARED_DICT=tracing_buffer 128m
      - KONG_LUA_PACKAGE_PATH=/home/kong/.luarocks/share/lua/5.1/?/?.lua;;
      - KONG_PLUGINS=bundled,skywalking
    entrypoint: ["bash", "-c", "kong migrations bootstrap", "kong start --vv"]
    depends_on: 
      postgres:
        condition: service_healthy
      oap:
        condition: service_healthy

  ui:
    image: apache/skywalking-ui:8.5.0
    ports:
      - 8080:8080
    environment:
      - SW_OAP_ADDRESS=oap:12800
    depends_on:
      oap:
        condition: service_healthy

